# ==============================================================================
# ==============================================================================
#                      SYNTHETIC DATA — NOT OIL INDIA DATA                      
# ------------------------------------------------------------------------------
# All data generated by this script is 100% SYNTHETIC, SIMULATED and FICTIONAL.
# Produced strictly for SIH26121 architectural and algorithmic demonstration.
# No confidential, proprietary, or actual Oil India Ltd operational data is used.
# ==============================================================================
# ==============================================================================

import os
import csv
import json
import math
import random
import uuid
from datetime import datetime, timedelta, timezone

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

BANNER_TEXT = """
================================================================================
                    SYNTHETIC DATA — NOT OIL INDIA DATA                         
All records, formations, drilling parameters, events, and reports are simulated.
================================================================================
"""

random.seed(42)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = BASE_DIR
REPORTS_DIR = os.path.join(OUTPUT_DIR, "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

# 15km field radius around Nahorkatiya field coordinates (Assam)
CENTER_LAT = 27.2800
CENTER_LON = 95.3400

FORMATION_TEMPLATES = [
    {"code": "F1", "name": "Alluvium / Dihing Formation", "lithology": "Unconsolidated sands, gravels, clays", "thickness": (350, 500)},
    {"code": "F2", "name": "Tipam Sandstone Formation", "lithology": "Medium to coarse grained sandstone", "thickness": (800, 1100)},
    {"code": "F3", "name": "Barail Coal-Shale Formation (F3)", "lithology": "Carbonaceous shale, coal seams, tight sandstone", "thickness": (400, 550)},
    {"code": "F4", "name": "Kopili Shale Formation", "lithology": "Splintery dark grey shale, calcareous silt", "thickness": (300, 450)},
    {"code": "F5", "name": "Sylhet Limestone Formation", "lithology": "Hard fossiliferous limestone with vugs", "thickness": (250, 400)},
    {"code": "F6", "name": "Basement Metamorphic Complex", "lithology": "Gneiss and quartzite basement", "thickness": (200, 350)},
]


def generate_dataset():
    print(BANNER_TEXT)

    wells = []
    formations = []
    mitigations = []
    reports = []
    report_chunks = []
    drilling_events = []
    drilling_parameters = []
    telemetry = []

    # -------------------------------------------------------------------------
    # 1. Generate 15 Wells within ~15km radius
    # -------------------------------------------------------------------------
    well_codes = [f"DEMO-WELL-{100 + i}" for i in range(1, 16)]
    statuses = ["active", "completed", "completed", "active", "completed"]

    for i, code in enumerate(well_codes):
        w_id = str(uuid.uuid4())
        # 15km is roughly ~0.135 degrees radius
        angle = random.uniform(0, 2 * math.pi)
        dist_km = random.uniform(0.5, 14.5)
        # 1 deg lat ~ 111km, 1 deg lon ~ 99km at lat 27
        d_lat = (dist_km * math.cos(angle)) / 111.0
        d_lon = (dist_km * math.sin(angle)) / 99.0

        lat = round(CENTER_LAT + d_lat, 6)
        lon = round(CENTER_LON + d_lon, 6)
        td = round(random.uniform(3300.0, 3950.0), 1)
        spud = datetime(2025, 1, 10, tzinfo=timezone.utc) + timedelta(days=i * 22)
        status = statuses[i % len(statuses)]

        wells.append({
            "well_id": w_id,
            "name": f"Nahorkatiya Exploration {code}",
            "code": code,
            "latitude": lat,
            "longitude": lon,
            "geom_wkt": f"SRID=4326;POINT({lon} {lat})",
            "spud_date": spud.strftime("%Y-%m-%d %H:%M:%S"),
            "total_depth_m": td,
            "status": status,
        })

    # Designate Wells A, B, C (index 0, 1, 2) for the correlated risk cluster
    cluster_well_indices = [0, 1, 2]
    # Ensure 8 of 15 wells have formation F3 (including Wells A, B, C)
    f3_well_indices = set(cluster_well_indices + [3, 4, 5, 6, 7])

    # -------------------------------------------------------------------------
    # 2. Formations per well (4-6 formations, F3 in 8 of 15 wells)
    # -------------------------------------------------------------------------
    well_f3_map = {}  # well_id -> f3_formation_dict

    for idx, w in enumerate(wells):
        include_f3 = idx in f3_well_indices
        num_formations = random.randint(4, 6)
        
        # Build sequence of templates for this well
        if include_f3:
            # F1, F2, F3, F4, [F5, F6]
            seq = [FORMATION_TEMPLATES[0], FORMATION_TEMPLATES[1], FORMATION_TEMPLATES[2]]
            for extra in FORMATION_TEMPLATES[3:num_formations]:
                seq.append(extra)
        else:
            # Skip F3: F1, F2, F4, F5, F6
            seq = [FORMATION_TEMPLATES[0], FORMATION_TEMPLATES[1], FORMATION_TEMPLATES[3]]
            for extra in [FORMATION_TEMPLATES[4], FORMATION_TEMPLATES[5]]:
                if len(seq) < num_formations:
                    seq.append(extra)

        curr_top = 0.0
        for form_tmpl in seq:
            form_id = str(uuid.uuid4())
            is_f3 = (form_tmpl["code"] == "F3")

            if is_f3:
                # Target F3 depth band: Top around 2680-2720m, Base around 2880-2950m
                top = 2700.0 + random.uniform(-25.0, 20.0)
                # Adjust previous bottom if needed
                if formations and formations[-1]["well_id"] == w["well_id"]:
                    formations[-1]["base_depth_m"] = round(top, 1)
                curr_top = top
                base = curr_top + random.uniform(200.0, 250.0)
            else:
                thick = random.uniform(*form_tmpl["thickness"])
                top = curr_top
                base = min(w["total_depth_m"], top + thick)

            top = round(top, 1)
            base = round(base, 1)
            curr_top = base

            f_obj = {
                "formation_id": form_id,
                "well_id": w["well_id"],
                "name": form_tmpl["name"],
                "top_depth_m": top,
                "base_depth_m": base,
                "lithology": form_tmpl["lithology"],
            }
            formations.append(f_obj)

            if is_f3:
                well_f3_map[w["well_id"]] = f_obj

    # -------------------------------------------------------------------------
    # 3. Reports & Chunks (Daily Drilling Reports for OCR/NLP)
    # -------------------------------------------------------------------------
    well_reports_map = {}  # well_id -> report_dict

    for w in wells:
        r_id = str(uuid.uuid4())
        file_name = f"{w['code']}_daily_drilling_report.pdf"
        file_path = f"synthetic_data/reports/{file_name}"
        
        r_obj = {
            "report_id": r_id,
            "well_id": w["well_id"],
            "report_type": "Daily Drilling Report",
            "file_path": file_path,
            "upload_date": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
        }
        reports.append(r_obj)
        well_reports_map[w["well_id"]] = r_obj

        # Create report chunks (mock embeddings)
        for page_num in range(1, 6):
            c_id = str(uuid.uuid4())
            chunk_text = f"Report for {w['name']} ({w['code']}) page {page_num}: Operations at depth {page_num * 600}m. Mud parameters normal. Routine formation evaluation."
            report_chunks.append({
                "chunk_id": c_id,
                "report_id": r_id,
                "page_number": page_num,
                "raw_text": chunk_text,
                "embedding": [round(random.gauss(0, 1), 5) for _ in range(384)],
            })

    # -------------------------------------------------------------------------
    # 4. INTENTIONALLY INJECT CORRELATED RISK CLUSTER (Wells A, B, C)
    #    Formation F3, depth band 2745 - 2770m, mud_loss or stuck_pipe, with mitigations
    # -------------------------------------------------------------------------
    cluster_specs = [
        {
            "well_idx": 0,  # Well A
            "type": "mud_loss",
            "depth": 2752.4,
            "severity": "critical",
            "page": 3,
            "desc": "CORRELATED CLUSTER INCIDENT: Severe mud loss of 120 bbl/hr in Barail Coal-Shale (F3) at 2752.4m upon traversing micro-fractured zone. Total pit volume drop 310 bbl.",
            "action": "Halted drilling immediately. Spotted 60 bbl high-fluid-loss squeeze LCM pill with coarse calcium carbonate and mica flakes.",
            "outcome": "Well stabilized after 14 hrs. Mud losses reduced to zero seepage. Resumed drilling with adjusted ECD."
        },
        {
            "well_idx": 1,  # Well B
            "type": "stuck_pipe",
            "depth": 2761.8,
            "severity": "critical",
            "page": 3,
            "desc": "CORRELATED CLUSTER INCIDENT: Differential stuck pipe in Barail Coal-Shale (F3) at 2761.8m during directional survey. Overpull reached 140 klbs with string static.",
            "action": "Mixed and spotted 50 bbl oil-based lubricating freeing pill around BHA. Worked drillstring with maximum allowable torque and jarred downward.",
            "outcome": "Pipe freed after 9.5 hours of jarring. Reamed interval with increased PAC-R polymer concentration."
        },
        {
            "well_idx": 2,  # Well C
            "type": "mud_loss",
            "depth": 2758.2,
            "severity": "critical",
            "page": 3,
            "desc": "CORRELATED CLUSTER INCIDENT: Sudden mud loss of 95 bbl/hr in Barail Coal-Shale (F3) at 2758.2m matching offset incidents in Well A and Well B.",
            "action": "Pulled string 4 stands off bottom. Pumped dual-density fibrous LCM blend and reduced circulation rate to 350 gpm.",
            "outcome": "Loss zone sealed successfully. Non-productive time limited to 11 hours."
        },
    ]

    for spec in cluster_specs:
        target_well = wells[spec["well_idx"]]
        f3_formation = well_f3_map[target_well["well_id"]]
        report = well_reports_map[target_well["well_id"]]

        # Mitigation record
        mit_id = str(uuid.uuid4())
        mitigations.append({
            "mitigation_id": mit_id,
            "action_text": spec["action"],
            "outcome": spec["outcome"],
        })

        # Event record
        evt_id = str(uuid.uuid4())
        drilling_events.append({
            "event_id": evt_id,
            "well_id": target_well["well_id"],
            "formation_id": f3_formation["formation_id"],
            "depth_m": spec["depth"],
            "event_type": spec["type"],
            "severity": spec["severity"],
            "description": spec["desc"],
            "mitigation_id": mit_id,
            "report_id": report["report_id"],
            "page_number": spec["page"],
        })

    # -------------------------------------------------------------------------
    # 5. Add 50+ Additional Random Events Across Wells (to satisfy >= 50 events)
    # -------------------------------------------------------------------------
    noise_event_types = ["kick", "mud_loss", "stuck_pipe", "pressure_anomaly", "torque_anomaly", "other"]
    severities = ["low", "medium", "high"]

    event_templates = {
        "kick": ("Gas kick influx of {gain} bbls in {form} at {depth}m. SIDPP reached {sidpp} psi.", "Shut in on annular BOP, circulated out kick using Wait & Weight.", "Pore pressure controlled; weighted up mud."),
        "mud_loss": ("Partial mud loss of {rate} bbl/hr encountered in {form} at {depth}m.", "Added fine nut-plug and fiber sealants to active system.", "Losses cured; resumed controlled drilling."),
        "stuck_pipe": ("Tight hole and mechanical drag in {form} at {depth}m with {pull} klbs overpull.", "Pumped high-viscosity sweep pill and reamed section.", "String freed; hole cleared."),
        "pressure_anomaly": ("Unexpected 450 psi standpipe pressure spike at {depth}m in {form}.", "Checked surface lines, inspected bit nozzles.", "Flow verified normal."),
        "torque_anomaly": ("Severe rotational torque oscillation (up to 28,000 ft-lbs) at {depth}m.", "Reduced WOB, adjusted RPM to eliminate torsional stick-slip.", "Drilling smoothed out."),
        "other": ("LWD telemetry transmission drop out during penetration of {form} at {depth}m.", "Troubleshot mud pulser unit at surface.", "Signal restored."),
    }

    # Generate at least 50 total events (3 cluster + 49 noise = 52 total)
    target_noise_count = 50
    for _ in range(target_noise_count):
        w = random.choice(wells)
        w_forms = [f for f in formations if f["well_id"] == w["well_id"]]
        f = random.choice(w_forms)
        
        # Pick depth within formation range, avoiding 2745-2770m in F3
        if f["name"].startswith("Barail"):
            depth = round(random.choice([random.uniform(f["top_depth_m"], 2740.0), random.uniform(2775.0, f["base_depth_m"])]), 1)
        else:
            depth = round(random.uniform(f["top_depth_m"] + 10, f["base_depth_m"] - 10), 1)

        ev_type = random.choice(noise_event_types)
        sev = random.choice(severities)
        desc_tpl, act_tpl, out_tpl = event_templates[ev_type]

        desc = desc_tpl.format(gain=random.randint(10, 30), sidpp=random.randint(200, 500), rate=random.randint(20, 60), pull=random.randint(40, 80), form=f["name"].split()[0], depth=depth)
        act = act_tpl
        out = out_tpl

        # Create mitigation for some events
        has_mit = random.random() > 0.4
        mit_id = None
        if has_mit:
            mit_id = str(uuid.uuid4())
            mitigations.append({
                "mitigation_id": mit_id,
                "action_text": act,
                "outcome": out,
            })

        report = well_reports_map[w["well_id"]]
        page_num = random.randint(1, 5)

        drilling_events.append({
            "event_id": str(uuid.uuid4()),
            "well_id": w["well_id"],
            "formation_id": f["formation_id"],
            "depth_m": depth,
            "event_type": ev_type,
            "severity": sev,
            "description": desc,
            "mitigation_id": mit_id,
            "report_id": report["report_id"],
            "page_number": page_num,
        })

    # -------------------------------------------------------------------------
    # 6. Generate Drilling Parameters Time Series per well
    # -------------------------------------------------------------------------
    for w in wells:
        base_depth = 1000.0
        max_d = w["total_depth_m"]
        step = 50.0  # every 50 meters
        curr_d = base_depth
        ts_base = datetime(2025, 2, 1, 8, 0, tzinfo=timezone.utc)
        step_idx = 0

        while curr_d <= max_d:
            # Realistic engineering parameter distributions with depth
            rop = round(max(3.0, random.gauss(18.0 - (curr_d / 300.0), 3.0)), 2)
            rpm = round(random.gauss(110.0, 10.0), 1)
            torque = round(random.gauss(12000.0 + (curr_d * 2.5), 1200.0), 1)
            mw = round(random.gauss(10.2 + (curr_d / 2000.0), 0.2), 2)
            pres = round(random.gauss(2400.0 + (curr_d * 0.45), 150.0), 1)
            ts = ts_base + timedelta(hours=step_idx * 3)

            drilling_parameters.append({
                "param_id": str(uuid.uuid4()),
                "well_id": w["well_id"],
                "depth_m": round(curr_d, 1),
                "rop": rop,
                "rpm": rpm,
                "torque": torque,
                "mud_weight": mw,
                "pressure": pres,
                "ts": ts.strftime("%Y-%m-%d %H:%M:%S"),
            })

            # Also generate telemetry record
            telemetry.append({
                "telemetry_id": str(uuid.uuid4()),
                "well_id": w["well_id"],
                "depth_m": round(curr_d, 1),
                "params": {"rop_m_hr": rop, "rpm": rpm, "torque_ft_lbs": torque, "mud_weight_ppg": mw, "spp_psi": pres},
                "ts": ts.strftime("%Y-%m-%d %H:%M:%S"),
            })

            curr_d += step
            step_idx += 1

    # -------------------------------------------------------------------------
    # 7. Generate Synthetic Daily Drilling Report PDFs (ReportLab)
    #    Narrative text with exact page numbers matching drilling_events.page_number
    # -------------------------------------------------------------------------
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('RptTitle', parent=styles['Heading1'], fontSize=16, textColor=colors.HexColor('#0f172a'), spaceAfter=4)
    banner_style = ParagraphStyle('RptBanner', parent=styles['Normal'], fontSize=9, textColor=colors.HexColor('#b91c1c'), fontName='Helvetica-Bold', spaceAfter=8)
    head_style = ParagraphStyle('RptHead', parent=styles['Heading2'], fontSize=11, textColor=colors.HexColor('#1e40af'), spaceBefore=6, spaceAfter=4)
    body_style = ParagraphStyle('RptBody', parent=styles['Normal'], fontSize=8.5, textColor=colors.HexColor('#334155'), spaceAfter=4)
    code_style = ParagraphStyle('RptCode', parent=styles['Normal'], fontSize=8, fontName='Courier', textColor=colors.HexColor('#0f172a'))

    print(f"Generating synthetic PDF daily reports in {REPORTS_DIR}...")
    for w in wells:
        pdf_path = os.path.join(OUTPUT_DIR, w["code"] + "_daily_drilling_report.pdf")
        # Ensure it also lives in synthetic_data/reports/
        target_pdf_path = os.path.join(REPORTS_DIR, f"{w['code']}_daily_drilling_report.pdf")
        
        doc = SimpleDocTemplate(target_pdf_path, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        story = []

        w_events = [e for e in drilling_events if e["well_id"] == w["well_id"]]

        # Build 5 pages matching page numbers
        for page_idx in range(1, 6):
            story.append(Paragraph("OIL INDIA LIMITED (SIMULATED OPERATIONS)", title_style))
            story.append(Paragraph("SYNTHETIC DATA — NOT OIL INDIA DATA · DEMO USE ONLY", banner_style))
            story.append(Paragraph(f"DAILY DRILLING REPORT — {w['name']} ({w['code']}) — PAGE {page_idx}", head_style))
            
            # Well info table
            meta_rows = [
                ["Field / Block:", "Nahorkatiya Basin", "Well Status:", w["status"].upper()],
                ["Coordinates:", f"Lat {w['latitude']} N, Lon {w['longitude']} E", "Total Depth:", f"{w['total_depth_m']} m"],
                ["Spud Date:", w["spud_date"][:10], "Current Report Page:", f"Page {page_idx} of 5"],
            ]
            t_meta = Table(meta_rows, colWidths=[100, 180, 100, 160])
            t_meta.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f1f5f9')),
                ('FONTSIZE', (0,0), (-1,-1), 8),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ]))
            story.append(t_meta)
            story.append(Spacer(1, 8))

            # Narrative operational log for this page
            story.append(Paragraph(f"Operations Log (Depth interval: {(page_idx-1)*700}m - {page_idx*700}m):", head_style))
            story.append(Paragraph(
                f"Drilling string operated with PDC bit. Rotational speed maintained between 100-120 RPM. "
                f"Circulated drilling fluid; monitored flow-out and return temperatures. Continuous mud-gas "
                f"chromatograph readings recorded. Formation markers evaluated against seismic prognoses.",
                body_style
            ))

            # Check if any events occurred on this page
            page_events = [e for e in w_events if e["page_number"] == page_idx]
            if page_events:
                story.append(Paragraph("CRITICAL DRILLING INCIDENTS & ACTIONS TAKEN ON THIS PAGE:", head_style))
                for pev in page_events:
                    story.append(Paragraph(f"• <b>EVENT: {pev['event_type'].upper()} at {pev['depth_m']}m (Severity: {pev['severity'].upper()})</b>", body_style))
                    story.append(Paragraph(f"  <i>Description:</i> {pev['description']}", body_style))
                    if pev["mitigation_id"]:
                        mit = next((m for m in mitigations if m["mitigation_id"] == pev["mitigation_id"]), None)
                        if mit:
                            story.append(Paragraph(f"  <b>Mitigation Action:</b> {mit['action_text']}", body_style))
                            story.append(Paragraph(f"  <b>Outcome:</b> {mit['outcome']}", body_style))
            else:
                story.append(Paragraph("Routine drilling progress maintained with no critical incidents logged during this reporting window.", body_style))

            if page_idx < 5:
                story.append(PageBreak())

        doc.build(story)

    # -------------------------------------------------------------------------
    # 8. Export structured CSV and JSON datasets
    # -------------------------------------------------------------------------
    export_payload = {
        "disclaimer": "SYNTHETIC DATA — NOT OIL INDIA DATA",
        "wells": wells,
        "formations": formations,
        "mitigations": mitigations,
        "reports": reports,
        "report_chunks": report_chunks,
        "drilling_events": drilling_events,
        "drilling_parameters": drilling_parameters[:100],  # sample for JSON
        "telemetry": telemetry[:100],
    }

    json_path = os.path.join(OUTPUT_DIR, "dataset.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(export_payload, f, indent=2)

    # Write CSVs
    def write_csv(filename, rows, fieldnames):
        filepath = os.path.join(OUTPUT_DIR, filename)
        with open(filepath, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            for r in rows:
                writer.writerow(r)

    write_csv("wells.csv", wells, ["well_id", "name", "code", "latitude", "longitude", "geom_wkt", "spud_date", "total_depth_m", "status"])
    write_csv("formations.csv", formations, ["formation_id", "well_id", "name", "top_depth_m", "base_depth_m", "lithology"])
    write_csv("mitigations.csv", mitigations, ["mitigation_id", "action_text", "outcome"])
    write_csv("reports.csv", reports, ["report_id", "well_id", "report_type", "file_path", "upload_date"])
    write_csv("drilling_events.csv", drilling_events, ["event_id", "well_id", "formation_id", "depth_m", "event_type", "severity", "description", "mitigation_id", "report_id", "page_number"])

    print("--------------------------------------------------------------------------------")
    print(f"Generated:")
    print(f"  - Wells: {len(wells)} (Clustered within 15km field radius)")
    print(f"  - Formations: {len(formations)} (Formation F3 present in 8 of 15 wells)")
    print(f"  - Drilling Events: {len(drilling_events)} (Correlated 3-well cluster in F3 at 2745-2770m + noise)")
    print(f"  - Mitigations: {len(mitigations)}")
    print(f"  - Reports: {len(reports)} (PDF files created in synthetic_data/reports/)")
    print(f"  - Drilling Parameters: {len(drilling_parameters)} time-series entries")
    print("================================================================================")

    return {
        "wells": wells,
        "formations": formations,
        "mitigations": mitigations,
        "reports": reports,
        "report_chunks": report_chunks,
        "drilling_events": drilling_events,
        "drilling_parameters": drilling_parameters,
        "telemetry": telemetry,
    }


if __name__ == "__main__":
    generate_dataset()
